# Generated by Django 5.1.4 on 2025-04-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapID', models.IntegerField()),
                ('investigationName', models.CharField(max_length=255)),
                ('investigationResult', models.TextField()),
                ('investigationDate', models.DateField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='healthcare.patient')),
            ],
        ),
    ]
