# Generated by Django 5.1.4 on 2025-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visitResult',
            field=models.TextField(blank=True, null=True),
        ),
    ]
